version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - C:/Users/Admin/movies:/media:ro
      # - C:/Users/Admin/anime:/anime:ro
    restart: unless-stopped

volumes:
  jellyfin-config:
  jellyfin-cache:
